# Generated by Django 5.1.4 on 2026-06-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="selected_index",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Dernier index (0 à 3) choisi par l'utilisateur (None si pas répondu).",
                null=True,
            ),
        ),
    ]
